export { router as userRouter } from './userRouter'
export { router as teamRouter } from './teamRouter'
export { router as tournamentRouter } from './tournamentRouter'
export { router as swuRouter } from './swuRouter'
export { router as snakesRouter } from './snakesRouter'
