#!/usr/bin/env bash

(cd ./server; yarn)
(cd ./client; yarn)

if [ ! -f "./scripts/env-local.yml" ]; then
cat > ./scripts/env-local.yml <<EOL
GITHUB_CLIENT_ID: <fill in your own here>
GITHUB_CLIENT_SECRET: <fill in your own here>
GITHUB_CALLBACK_URL: http://localhost:3009/auth/github/callback
AUTH_REDIRECT_URL: http://localhost:3000
BATTLESNAKE_SERVER_HOST: http://localhost:3001
REDIS_HOST: localhost
COOKIE_DOMAIN: localhost
EOL
fi

if [ ! -f "./scripts/.env" ]; then
cat > ./scripts/.env <<EOL
REACT_APP_SERVER=http://localhost:3009
EOL
fi
