#!/usr/bin/env bash

(cd ./server; yarn)
(cd ./client; yarn)

cat > ./scripts/env-local.yml <<EOL
GITHUB_CLIENT_ID: <fill in your own here>
GITHUB_CLIENT_SECRET: <fill in your own here>
GITHUB_CALLBACK_URL: http://localhost:3000/auth/github/callback
REDIS_HOST: localhost
BATTLESNAKE_SERVER_HOST: http://localhost:3001
EOL
