#!/bin/bash

args_list=($@)
num_args=${#args_list[@]}
if [ $num_args = 3 ]; then
  username=$args_list
else
  read -p "username: " username
fi

# read -p "snakeUrl: " snakeUrl
# read -p "boardWidth: " boardWidth
# read -p "boardHeight: " boardHeight
# read -p "maxFood: " maxFood
# read -p "snakeStartLength: " snakeStartLength
# read -p "decHealthPoints: " decHealthPoints
# read -p "pinTail: " pinTail

cat > dynamo-input.json <<EOF
{
  "TableName": "users",
  "ReturnValues": "ALL_NEW",
  "ReturnConsumedCapacity": "NONE",
  "ReturnItemCollectionMetrics": "NONE",
  "UpdateExpression": "set bountyCollector = :m",
  "ExpressionAttributeValues": {
    ":m": {
      "BOOL": true
    }
  }
}
EOF

aws dynamodb update-item $DYNAMO_FLAGS --table-name users --key "{\"username\": {\"S\": \"${username}\"}}" --cli-input-json="$(cat dynamo-input.json)" $@
rm dynamo-input.json
